### PR TITLE
Update sensors_mqtt.py

### PR DESCRIPTION
**Pull request by Benchamoneh**
Modify "Battery Charging Power" sensor to look for "pcharge1" instead of "p1charge1"

### CODE REVIEW

**Comment by Benchamoneh** [comment]
To fix issue

Sensor missing: Battery Charging Power #19

**Comment by muppet3000** [comment]
As discussed over on #19 this would break the implementation of this feature for SPH systems, so I've submitted another commit with this lookup instead.

**Comment by Benchamoneh** [comment]
Your commit works perfectly, thanks

**Comment by muppet3000** [comment]
> Your commit works perfectly, thanks

This is the sort of shit I could do with hearing at work every day :P

**Pull request closed without merging**
